# Generated by Django 3.1.2 on 2020-12-22 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201223_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 19, 29, 24, 813074, tzinfo=utc)),
        ),
    ]
